### ISSUE TITLE
Not working. How to check?

### ISSUE THREAD

**Issue by oleua** [R0Wi/elasticsearch-nextcloud-docker#2]
I started the container, trying to check with `telnet 127.0.0.1 9200` and constantly getting Connection refused error.
The same about trying with `curl -L http://127.0.0.1:9200` and getting Connection reset by peer.
How to check whether the service is working?

UPD: disabled machine learning with `xpack.ml.enabled=false` and it's started!

**Comment by R0Wi** [comment]
I don't see why Machine Learning should stop you from connecting. Please check the official docs and try "docker logs" to investigate. Cheers
