### ISSUE TITLE
Nextcloud doesn't show the results of context search 

### ISSUE THREAD

**Issue by oleua** [R0Wi/elasticsearch-nextcloud-docker#3]
I have used to use the elasticsearch installed directly on the server. Now I am trying to migrate to the docker. Docker is working fine with the version 7.6.0. I have changed the path to the data directory to /var/lib/elasticsearch in order to use the existing there data.

However, Nextcloud doesn't show in the search result the section for fulltext search.

Please, advise, what to do?

**Comment by oleua** [comment]
I've made some studies, and found: This is not working (no fulltext search section and the occ fulltextsearch:search doesn't give any result):
```
{
  "name" : "abc.local",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "cnN1EM3CRGy66wD4nO0-vg",
  "version" : {
    "number" : "7.6.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "7f634e9f44834fbc12724506cc1da681b0c3b1e3",
    "build_date" : "2020-02-06T00:09:00.449973Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```
and this is working:

```
{
  "name" : "abc.local",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "OIUDcH-ZTcWHKbkYzCvJiA",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by Happyfeet01** [comment]
For me is it working with the fastest Version 26.0.0.
Have the made an check, or test? Use the elasticsearch Version 8.6.1 for search. 

My index is running since this night. I wait for finishing it.

**Comment by R0Wi** [comment]
> For me is it working with the fastest Version 26.0.0. Have the made an check, or test? Use the elasticsearch Version 8.6.1 for search.
> 
> My index is running since this night. I wait for finishing it.

I'm using the same combination: Nextcloud 26 (with the FTS stack also installed on version 26) together with Elastic 8.6.1.

**Comment by Happyfeet01** [comment]
Index is finished, but for my black design of NC the searchresult is unreadable 🙈 
![Screenshot_20230605-081638_Fennec](https://github.com/R0Wi/elasticsearch-nextcloud-docker/assets/3295104/1d2b354f-fc70-42f0-a0d4-17ad17bb0ab4)

**Comment by R0Wi** [comment]
Yeah but that's a frontend design issue within the `fulltextsearch` app 😄 Search seems to work for you aswell? Btw: if you're using the NC mobile app, this will also work fine together with FTS since FTS implements the unified search (and the mobile app will display properly formatted results on your phone) 👍

**Comment by Happyfeet01** [comment]
Oh nice, thanks for this Tip.

**Comment by oleua** [comment]
Hey colleagues. I have migrated to the ES docker service, and I am trying to index the data and let them be shown in the webUI. What I've got that they are shown only partially with the least minimum, and no new data are appearing.

Which may be the algorithm to reindex them? I've tried to make fulltextsearch:index several times without much success.
