### ISSUE TITLE
How to migrate to ES docker service?

### ISSUE THREAD

**Issue by oleua** [R0Wi/elasticsearch-nextcloud-docker#4]
Hi! Would you please consult the process of migrating data from the elasticsearch which is installed directly on the server to the docker service without loss? Please, give steps and caveats which may exist on this way. Personally me, I wasn't luck with just running fulltextsearch:index command, which gave partial result after completion.

**Comment by R0Wi** [comment]
I'm sorry but I need to mention that this is not the right place to ask for migration instructions or general how-to-guides related to Nextcloud and Elasticsearch. This is just a Docker base image which fullfills all the requirements needed by the Nextcloud Fulltextsearch App. If you're facing problems with the latter, please reach out to the NC support forum or the Discussion/Issue tracker of the app itself. I'd recommend you decrease your NC loglevel and inspect your logs after you've run your commands.

If you need personal assistance I'd be happy to connect offline. If you like, just drop me a private message.
