### ISSUE TITLE
Add log facility

### ISSUE THREAD

**Issue by oleua** [R0Wi/elasticsearch-nextcloud-docker#6]
Hi! Please, add to your description the following options to the docker file:
```
-v /app/elasticsearch/log:/usr/share/elasticsearch/logs
-v /app/elasticsearch/data:/usr/share/elasticsearch/data
```
What I've got that the directories logs and data should have 775 mask.

**Comment by R0Wi** [comment]
The data volume is already mentioned in the docs. Regarding logging, the container logs to stdout, which is kinda best practice for docker containers. So you should be able to show the ES logs via `docker logs` or `docker-compose logs`.

**Comment by R0Wi** [comment]
Btw: the docker log files can be found at `/var/lib/docker/containers/<container id>/<container id>-json.log` (see https://stackoverflow.com/questions/33017329/where-is-a-log-file-with-logs-from-a-container). If you need to print them to another file, just use something like `docker logs <ES container id> > mylog.txt`. Hope this helps!
