### ISSUE TITLE
"failed to obtain node locks" error 

### ISSUE THREAD

**Issue by zeigerpuppy** [R0Wi/elasticsearch-nextcloud-docker#7]
It looks like the permissions for a secure elasticsearch container don't bootstrap properly any more.

If you get error "failed to obtain node locks" in the logs, then you may need to set the volume to the following permissions:

1. set a local volume:

```yaml
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
```

Create the storage dir and change permissions

```bash
mkdir elasticsearch_data
chown -R 1000:0 ./elasticsearch_data/
```

The container will then start without error

> note that this applies to the official elasticsearch image too
> note this is using image tag 8.6.1

**Comment by R0Wi** [comment]
I started a fresh instance like documented in the README like this:

```bash
docker run -d \
    -v elastic_data:/usr/share/elasticsearch/data \
    -p 127.0.0.1:9200:9200 \
    -e "cluster.name=docker-cluster" \
    -e "bootstrap.memory_lock=true" \
    -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
    -e "discovery.type=single-node" \
    -e "xpack.security.enabled=false" \
    --restart always \
    r0wi/elasticsearch-nextcloud-docker:8.6.1
```

But I'm not able to see the locks error you're talking about. Everything works as expected. Did you come from an earlier ES version?

**Comment by R0Wi** [comment]
Any feedback?
